### ISSUE TITLE
Create commands for latex macros

### ISSUE THREAD

**Issue by appositum** [sqdorte/saturn#2]
- [ ] Pinto De Travesti gay `=tex \rho\mathfrak{i}\eta\tau\Theta \\ \mathbb{D}\epsilon \\ \Gamma\mathbb{R}\alpha\nu\Sigma\mathfrak{S}\top{i} \\ \Game\Delta\Upsilon`
- [ ] Fodase fudido `=tex \digamma\Theta\mathbb{D}\alpha\mathfrak{S}\exists \ {f}\mu\delta\imath\mathfrak{d}\theta`
- [ ] CU `=tex \subset\cup`
- [ ] Cu TOp `=tex \complement\cup \ \top\Theta\rho`
- [ ] GOSTOSA `=tex \Game\Theta\mathbb{S}\top\bigodot\mathfrak{S}\forall`
- [ ] Min da Seu CU `=tex \mathfrak{M}\imath\eta \\  \delta\alpha \\ \mathbb{S}\epsilon\mu \\ \subset\cup`
- [ ] uMa MiGAlHA De BUCEta pFv `=tex \mu{M}\alpha \\ \mathfrak{M}\imath\reflectbox{$\Game$}\Delta\iota\mathbb{H}\forall \\ \mathbb{D}\epsilon \\ \beta\cup\subset\Sigma\tau\alpha \\ \rho\digamma\nu`
- [ ] TA `=tex \rotatebox{180}{$\forall\bot$}`

**Comment by sqdorte** [comment]
vo analisa e desenvolvo

**Comment by sqdorte** [comment]
- [ ] Calado aberrasao
`
=tex \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \  \ \  \ \ \mathbb{C} \alpha \text{l} \reflectbox{4} \mathfrak{D} \theta \ \alpha \beta \Sigma \mathbb{R} \reflectbox{R} \text{A} \mathfrak{SS} \alpha \bigodot \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \  \ \  \ \  \rotatebox{90}{$\implies$} \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \  \ \  \ \rotatebox{60}{$\implies$} \ \implies \rotatebox{10}{$\implies$} \rotatebox{40}{$\implies$}
`

**Comment by appositum** [comment]
[WIP](https://github.com/appositum/saturn/tree/latex)
